### ISSUE TITLE
Monitoring Software Deployment

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/grid_deployment#53]
# Todo

- Develop procedures to
   - deploy monitoring software

# Related issue

- [See tfgrid validator stack main project issue for overview](https://github.com/threefoldtech/grid_deployment/issues/47)

**Comment by coesensbert** [comment]
This is just docs on how to monitor a grid backend stack? if so -> https://github.com/threefoldtech/grid_deployment/tree/development/docker-compose#metrics

Or we need tools to deploy a full prometheus/grafana/alertmanager stack? Since those already exist online, example: https://github.com/docker/awesome-compose/blob/master/prometheus-grafana/README.md

**Comment by mik-tf** [comment]
Yes I think as you said here, that it's already in the full grid stack, such as: https://metrics.grid.tf/d/rYdddlPWkfqwf/zos-host-metrics?orgId=2&refresh=5s

I'll check on my end but from what I understand, we got this with the full grid stack.

**Comment by mik-tf** [comment]
I confirm we have the necessary monitoring software with the current tfgrid full stack.
