### ISSUE TITLE
Playground is outdated and shouldn't be deployed

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_deployment#75]
Playground is outdated and shouldn't be deployed; instead, the dashboard is the one that should be used.

```
    environment:
      MODE: main
      PLAYGROUND_URL: https://play.harbydomain.gridtesting.xyz
```

**Comment by coesensbert** [comment]
playground is not deployed anymore. The following repo was given by dev to fetch the dashboard: https://github.com/threefoldtech/grid_deployment/blob/development/docker-compose/mainnet/docker-compose.yml#L286
Since the creation of the dashboard, there have been some legacy playground references. If these need changing, please let us know

this env variable was also instructed to us: https://github.com/threefoldtech/grid_deployment/blob/development/docker-compose/mainnet/docker-compose.yml#L298

**Comment by mik-tf** [comment]
@A-Harby please let us know if there are any places we need to update from playground to dashboard. Thanks!

**Comment by A-Harby** [comment]
> @A-Harby please let us know if there are any places we need to update from playground to dashboard. Thanks!

No, its only this till now.

**Comment by coesensbert** [comment]
none-issue
